name: workflow test
run-name: workflow iniciado por @${{ github.actor }}

on:
  
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
      - name: Mostrando mensaje
        run: echo "Hola mundo"

